name: Test and Verify Source Code

on:
  push:
  pull_request:

jobs:
  check-requirements:
    name: Check minimum system requirements from README
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        include:
          - cxx: g++-9
            cc: gcc-9
          - cxx: clang++-9
            cc: clang-9
    env:
      CC: ${{matrix.cc}}
      CXX: ${{matrix.cxx}}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@master
        with:
          cmake-version: 3.12
      - name: Setup Ninja build tool
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: 1.4.0
          dest: /home/runner/.local/bin
      # A compiler is already installed; it was chosen in jobs.*.env.
      - name: Configure the project
        run: mkdir build && cd build && cmake -G Ninja ..
      - name: Try to build the project
        run: cmake --build build

  test-os-integration:
    name: Run tests of OS integration
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Configure the project
        run: mkdir build && cd build && cmake ..
      - name: Build the project
        run: cmake --build build --config Debug
      - name: Test the project
        run: ctest --build-config Debug -R OsIntegration.*
        working-directory: build
        env:
          CTEST_PARALLEL_LEVEL: 3

  test:
    name: Run tests of crossplatform components
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Configure the project
        run: mkdir build && cd build && cmake ..
      - name: Build the project
        run: cmake --build build --config Debug
      - name: Test the project
        run: ctest --build-config Debug -E OsIntegration.*
        working-directory: build
        env:
          CTEST_PARALLEL_LEVEL: 3
